
export const Nav={
    Welcome:"Welcome",
    Login:"login",
    Signup:"signup",
    Forgot:"forgot",
    Verify:"verify",
    Changepassword:"changep",
    loginAsMember:"loginAsMember",

    //user LogedIn
    Home:'home',
    HomeStack:'HomeStack',
    Search:'search',
    SearchTab:'searchTab',
    Searchmain:'Searchmain',
    Notifications:'Notifications',
    Rewards:'Rewards',
    CartSummry:'CartSummry',
    CartPayment:'CartPayment',
    OrderPlace:'OrderPlace',
    Wallet:'Wallet',
    Profile:'profile',
    News:'News',
    NewsDetails:'NewsDetails',
    Family:'family_screen',
    FamilyList:'FamilyList',
    FamilyHome:'FamilyHome',
    ServicesHome:'Services_home',
    Alnikkah:'Alnikkah',
    Barat:'Barat',
    FunritureHome:'FurnitureHome',
    FunrtitureDetailes:'funrinuteDetailes',
    SelectedFurniture:'SelectedFurniture',
    FurnitureList:'furnitureList',
    FoodAndFood:'FoodandFood',
    WeedingDress:'weedingDress',
    Saloon:'Saloon',
    Valima:'Valima',
    RentACar:'RentACar',

    Help:'Help',
    About:'About',
    RegisterFuneral:'RegisterFuneral',
    Mart: 'Mart',
    MartDetails: 'MartDetails',
    ECommerce:'ECommerce',
    Business:'Business',
    Jobs:'Jobs',
    JobDetails:'JobDetails',
    Hospital: 'Hospital',
    OPD:'OPD',
    Lab:'Lab',
    RegisterOpd:'RegisterOpd',
    MaleServices:'MaleServices',
    FemaleServices:'FemaleServices',
    RegisterShadi:'RegisterShadi',
    AffiliationHome:'AffiliationHome',
    BlogsList:'BlogsList',
    BlogDetails:'BlogDetails',
    VideosList:'VideosList',
    WatchVideo:'WatchVideo',
    ECommerceCart:'ECommerceCart',
    ECommDetails:'ECommDetails',
    AddValima:'AddValima',
    AddSaloon:'AddSaloon',
    AddBarat:'AddBarat',
    AddFood:'AddFood',
    ListFood:'ListFood',
    SelectedFood:'SelectedFood',
    AddDress:'AddDress',
    DressList:'DressList',
    SelectedDress:'SelectedDress',
    AddCar:'AddCar',
    CarList:'CarList',
    SelectedCar:'SelectedCar',
    appliancesList:'appliancesList',
    selectedAppliances:'selectedAppliances',
    appliances:'appliances',
    QuizHome:'QuizHome',
    QuizStart:'QuizStart',
    MartCart:'MartCart',
    CalculateResults:'CalculateResults'

}